# Generated by Django 4.1 on 2022-08-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mybooks',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
